"""Research workflow package."""

from market_platform.research.interpretation import (
    DIRECTIONAL_CURRENT_DRAWDOWN_SCALE,
    DIRECTIONAL_DISTANCE_FROM_MOVING_AVERAGE_SCALE,
    DIRECTIONAL_MOMENTUM_SCALE,
    DIRECTIONAL_TREND_SCALE,
    InterpretedSignal,
    InterpretedSignalState,
    SignalInterpretationRule,
    SignalRole,
    VolatilityAssessment,
    VolatilityState,
    calculate_research_composite_signal,
    interpret_directional_signals,
    interpret_market_signal,
    interpret_realized_volatility,
)
from market_platform.research.models import (
    MarketView,
    PositionAction,
    PositionContext,
    PriceContext,
    PriceLevel,
    PriceTarget,
    ProbabilityEstimate,
    ResearchAnalysis,
    ResearchCompositeAssessment,
    ResearchRequest,
    ResearchResult,
    ResearchSignalComponent,
    ResearchStatus,
    ResearchStructureAssessment,
    ResearchWarning,
    StrategyCandidate,
    StructuralTargetDirection,
    StructuralTargetLevel,
)
from market_platform.research.price_context import build_price_context
from market_platform.research.target_framework import build_structural_target_levels
from market_platform.research.workflow import DefaultResearchWorkflow, ResearchWorkflow

__all__ = [
    "DIRECTIONAL_CURRENT_DRAWDOWN_SCALE",
    "DIRECTIONAL_DISTANCE_FROM_MOVING_AVERAGE_SCALE",
    "DIRECTIONAL_MOMENTUM_SCALE",
    "DIRECTIONAL_TREND_SCALE",
    "InterpretedSignal",
    "InterpretedSignalState",
    "DefaultResearchWorkflow",
    "MarketView",
    "PositionAction",
    "PositionContext",
    "PriceContext",
    "PriceLevel",
    "PriceTarget",
    "ProbabilityEstimate",
    "ResearchAnalysis",
    "ResearchCompositeAssessment",
    "ResearchRequest",
    "ResearchResult",
    "ResearchSignalComponent",
    "ResearchStatus",
    "ResearchStructureAssessment",
    "ResearchWarning",
    "ResearchWorkflow",
    "SignalInterpretationRule",
    "SignalRole",
    "StructuralTargetDirection",
    "StructuralTargetLevel",
    "StrategyCandidate",
    "VolatilityAssessment",
    "VolatilityState",
    "build_price_context",
    "build_structural_target_levels",
    "calculate_research_composite_signal",
    "interpret_directional_signals",
    "interpret_market_signal",
    "interpret_realized_volatility",
]
